# Generated by Django 3.0.8 on 2020-10-30 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=50)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='zoopark.Human')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='zoopark.Place')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='zoopark.Variety')),
            ],
        ),
    ]
