# Generated by Django 3.0.8 on 2020-10-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0006_auto_20201031_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('М', 'мужской'), ('Ж', 'женский')], max_length=10),
        ),
        migrations.AlterField(
            model_name='human',
            name='gender',
            field=models.CharField(choices=[('М', 'мужской'), ('Ж', 'женский'), ('В', 'вертолёт'), ('?', 'лгбт'), ('Б', 'бэтмен')], max_length=10),
        ),
    ]
