# Generated by Django 3.0.8 on 2020-10-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0007_auto_20201031_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='day_human',
            new_name='month_human',
        ),
        migrations.AlterField(
            model_name='human',
            name='gender',
            field=models.CharField(choices=[('М', 'мужской'), ('Ж', 'женский'), ('?', 'лгбт')], max_length=10),
        ),
    ]
