# Generated by Django 3.0.8 on 2020-11-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0008_auto_20201031_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal',
            field=models.CharField(max_length=50, verbose_name='Животное'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('М', 'мужской'), ('Ж', 'женский')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='month_human',
            field=models.PositiveSmallIntegerField(verbose_name='Сколько месяцев уже закреплён сотрудник'),
        ),
        migrations.AlterField(
            model_name='human',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='human',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='human',
            name='experience',
            field=models.IntegerField(verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='human',
            name='gender',
            field=models.CharField(choices=[('М', 'мужской'), ('Ж', 'женский'), ('?', 'лгбт')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='human',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='human',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='place',
            name='capacity',
            field=models.IntegerField(verbose_name='Вместимость животных'),
        ),
        migrations.AlterField(
            model_name='place',
            name='height',
            field=models.IntegerField(verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='length',
            field=models.IntegerField(verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='place',
            name='material',
            field=models.CharField(max_length=30, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.CharField(max_length=30, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='place',
            name='width',
            field=models.IntegerField(verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='behavior',
            field=models.TextField(verbose_name='Описание вида'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='food',
            field=models.CharField(max_length=30, verbose_name='Питание'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='recommendation',
            field=models.TextField(verbose_name='Рекомендации по работе'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='variety',
            field=models.CharField(max_length=30, verbose_name='Вид'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
