# Generated by Django 3.0.8 on 2020-11-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0009_auto_20201101_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('tagline', models.CharField(default='', max_length=100, verbose_name='Слоган')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='movies/', verbose_name='Постер')),
                ('year', models.PositiveSmallIntegerField(default=2019, verbose_name='Дата выхода')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('budget', models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Бюджет')),
                ('fees_in_usa', models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Сборы в США')),
                ('fess_in_world', models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Сборы в мире')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('М', 'мужской'), ('Ж', 'женский'), ('Х', 'бесполый')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='human',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='human',
            name='experience',
            field=models.PositiveSmallIntegerField(verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='human',
            name='gender',
            field=models.CharField(choices=[('М', 'мужской'), ('Ж', 'женский'), ('В', 'вертолёт'), ('?', 'лгбт')], max_length=10, verbose_name='Пол'),
        ),
    ]
