# Generated by Django 3.0.8 on 2020-11-01 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0010_auto_20201101_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
    ]
