# Generated by Django 3.0.8 on 2020-11-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0012_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='animal',
            field=models.ManyToManyField(related_name='name_animal', to='zoopark.Animal', verbose_name='режиссер'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='month_human',
            field=models.PositiveSmallIntegerField(help_text='в месяцах', verbose_name='Сколько месяцев уже закреплён сотрудник'),
        ),
        migrations.AlterField(
            model_name='human',
            name='experience',
            field=models.PositiveSmallIntegerField(help_text='в годах', verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='human',
            name='name',
            field=models.CharField(help_text='на пейджике будет', max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='human',
            name='phone',
            field=models.CharField(help_text='не более 15 символов', max_length=15, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='place',
            name='capacity',
            field=models.IntegerField(help_text='сколько влезет животных', verbose_name='Вместимость животных'),
        ),
        migrations.AlterField(
            model_name='place',
            name='height',
            field=models.IntegerField(help_text='в метрах', verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='length',
            field=models.IntegerField(help_text='в метрах', verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='place',
            name='material',
            field=models.CharField(help_text='основной материал защиты', max_length=30, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='place',
            name='width',
            field=models.IntegerField(help_text='в метрах', verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='food',
            field=models.CharField(help_text='написать, что кушает животное', max_length=30, verbose_name='Питание'),
        ),
    ]
