# Generated by Django 3.0.8 on 2020-11-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0013_auto_20201102_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Животное', 'verbose_name_plural': 'Животные'},
        ),
        migrations.AlterModelOptions(
            name='human',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место животного', 'verbose_name_plural': 'Места животных'},
        ),
        migrations.AlterModelOptions(
            name='variety',
            options={'verbose_name': 'Вид животного', 'verbose_name_plural': 'Видов животных'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='animal',
        ),
    ]
